// Generated by lib/job-scheduler-bree.ts — do not edit.
'use strict';
const { parentPort } = require('node:worker_threads');
function report(outcome) {
  try { parentPort.postMessage({ type: 'run:result', ...outcome }); } catch {}
  process.exit(0);
}
(async () => {
  try {
    const REFS = {"bootstrap":"/Users/johnlynas/dev/nipp-0807/job-scheduler-runtime/job-scheduler-worker-bootstrap.cjs","service":"/Users/johnlynas/dev/nipp-0807/services/job-scheduler-service.ts","builtins":"/Users/johnlynas/dev/nipp-0807/lib/job-scheduler-builtins.ts","jobId":"cmu0do31y000gp9zwgzpb63ty"};
    // Per-worker loader (TypeScript + '@/…' alias; see bootstrap comment).
    require(REFS.bootstrap);
    const serviceModule = require(REFS.service);
    const builtins = require(REFS.builtins);
    serviceModule.JobSchedulerService.registerBuiltins(builtins.BUILTIN_HANDLERS);
    const res = await serviceModule.JobSchedulerService.runJob(REFS.jobId, { trigger: 'SCHEDULE' });
    report({ ok: true, run: res });
  } catch (err) {
    report({ ok: false, error: err && err.message ? err.message : String(err) });
  }
})();
