-- ============================================================
-- SUPERSEDED — no-op (kept for migration-history order only)
-- ============================================================
-- The policies originally drafted here were NEVER applied to any instance
-- (verified 2026-09-19: no _prisma_migrations table in the dev database,
-- and this file's statements were not present in pg_policies anywhere).
--
-- Superseded by: 20260919093000_rls_complete_policies — the authoritative,
-- complete 18-table RLS policy catalog (see documents/rls-complete-implementation.md §3.3).
-- ============================================================
