#!/usr/bin/env tsx
/**
 * Generate tests/isolation/database/policy-catalog.golden from a freshly
 * migrated scratch DB (owner role). The migrations-ownership.spec.ts spec
 * compares the live pg_policies catalog against this file byte-for-byte.
 *
 * Run:  npm run db:gen-policy-golden   (needs .env DATABASE_URL + NIPP_APP_DB_PASSWORD)
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { prepareDatabase } from '../tests/isolation/database/rls-fixture';

const root = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(root, '../tests/isolation/database/policy-catalog.golden');

main();

async function main() {
  const db = await prepareDatabase();
  try {
    const r = await db.owner.query(`
      SELECT tablename, policyname, cmd, coalesce(qual, '') AS qual
      FROM pg_policies
      WHERE schemaname = 'public' AND tablename NOT LIKE '_prisma_%'
      ORDER BY tablename, policyname, cmd`);
    const body = r.rows.map((x) => `${x.tablename} | ${x.policyname} | ${x.cmd} | ${x.qual}`).join('\n');
    writeFileSync(out, `# RLS policy catalog golden (design §5.1) — generated by scripts/rls-gen-policy-golden.ts\n` +
      `# Lines: TABLE | POLICY | CMD | qual  (sorted; compared byte-for-byte in migrations-ownership.spec.ts)\n` + body + '\n');
    console.log(`Wrote ${out} (${r.rows.length} policy lines)`);
  } finally {
    await db.close();
  }
}
