-- ============================================================
-- Chain catch-up: objects missing from migration history
-- ============================================================
-- The dev database was created with `prisma db push`, so several objects it
-- carries were NEVER present in any migration file; a fresh `migrate deploy`
-- failed (type "NotificationPriority" does not exist at job-scheduler, then
-- six missing tables). This migration reflects the verified dev nipp_dev
-- catalog (2026-09-19) so the chain is self-sufficient for fresh instances.
-- All statements are idempotent - a no-op on existing db-push databases,
-- authoritative on fresh `migrate deploy` runs. Generated by:
--   node scripts/rls-gen-missing-tables.mjs
-- Re-run that script after any schema change touching these objects and diff
-- its output against this migration file (drift check).
-- NOTE: enum labels are single-quoted — on Postgres 16+ the real labels
-- DAILY/WEEKLY are reserved keywords and unquoted CREATE TYPE fails. Type
-- NAMES are double-quoted (catalog stores them case-folded otherwise, which
-- breaks quoted references), and existence guards compare case-insensitively.
-- ============================================================

DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE lower(typname) = 'calendarrecurrencefrequency' AND typtype IN ('e','c')) THEN
    CREATE TYPE "CalendarRecurrenceFrequency" AS ENUM ('DAILY','WEEKLY','MONTHLY','QUARTERLY','SEMI_ANNUALLY','ANNUALLY');
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE lower(typname) = 'calendareventype' AND typtype IN ('e','c')) THEN
    CREATE TYPE "CalendarEventType" AS ENUM ('VIEWING','INSPECTION','MAINTENANCE','LEASE_SIGNING','LEASE_RENEWAL','KEY_EXCHANGE','OTHER');
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE lower(typname) = 'notificationpriority' AND typtype IN ('e','c')) THEN
    CREATE TYPE "NotificationPriority" AS ENUM ('INFO','WARNING','ERROR','CRITICAL','CALENDAR','JOB');
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE lower(typname) = 'notificationscope' AND typtype IN ('e','c')) THEN
    CREATE TYPE "NotificationScope" AS ENUM ('GLOBAL','ORG');
  END IF;
END $ddl$;

CREATE TABLE IF NOT EXISTS "Team" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "slug" text,
  "description" text,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "organizationId" text NOT NULL,
PRIMARY KEY ("id"),
FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Team_organizationId_name_idx') THEN
    CREATE INDEX "Team_organizationId_name_idx" ON "Team" USING btree ("organizationId", name);
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Team_slug_idx') THEN
    CREATE INDEX "Team_slug_idx" ON "Team" USING btree (slug);
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Team_organizationId_slug_key') THEN
    CREATE UNIQUE INDEX "Team_organizationId_slug_key" ON "Team" USING btree ("organizationId", slug);
  END IF;
END $ddl$;

CREATE TABLE IF NOT EXISTS "Calendar" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "color" text DEFAULT '#1B2A4A'::text NOT NULL,
  "isDefault" BOOLEAN DEFAULT false NOT NULL,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "organizationId" text NOT NULL,
PRIMARY KEY ("id"),
FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Calendar_organizationId_idx') THEN
    CREATE INDEX "Calendar_organizationId_idx" ON "Calendar" USING btree ("organizationId");
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Calendar_organizationId_name_key') THEN
    CREATE UNIQUE INDEX "Calendar_organizationId_name_key" ON "Calendar" USING btree ("organizationId", name);
  END IF;
END $ddl$;

CREATE TABLE IF NOT EXISTS "TeamMember" (
  "id" text NOT NULL,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "teamId" text NOT NULL,
  "userId" text NOT NULL,
  "organizationId" text NOT NULL,
PRIMARY KEY ("id"),
FOREIGN KEY ("teamId") REFERENCES "Team" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ("userId") REFERENCES "User" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='TeamMember_organizationId_idx') THEN
    CREATE INDEX "TeamMember_organizationId_idx" ON "TeamMember" USING btree ("organizationId");
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='TeamMember_teamId_idx') THEN
    CREATE INDEX "TeamMember_teamId_idx" ON "TeamMember" USING btree ("teamId");
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='TeamMember_userId_teamId_key') THEN
    CREATE UNIQUE INDEX "TeamMember_userId_teamId_key" ON "TeamMember" USING btree ("userId", "teamId");
  END IF;
END $ddl$;

CREATE TABLE IF NOT EXISTS "TeamRole" (
  "id" text NOT NULL,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "teamId" text NOT NULL,
  "roleId" text NOT NULL,
  "organizationId" text NOT NULL,
PRIMARY KEY ("id"),
FOREIGN KEY ("teamId") REFERENCES "Team" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ("roleId") REFERENCES "Role" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='TeamRole_organizationId_idx') THEN
    CREATE INDEX "TeamRole_organizationId_idx" ON "TeamRole" USING btree ("organizationId");
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='TeamRole_teamId_roleId_key') THEN
    CREATE UNIQUE INDEX "TeamRole_teamId_roleId_key" ON "TeamRole" USING btree ("teamId", "roleId");
  END IF;
END $ddl$;

CREATE TABLE IF NOT EXISTS "CalendarEvent" (
  "id" text NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "startDate" TIMESTAMP(3) NOT NULL,
  "endDate" TIMESTAMP(3) NOT NULL,
  "eventType" "CalendarEventType" DEFAULT 'OTHER'::"CalendarEventType" NOT NULL,
  "color" text,
  "calendarId" text NOT NULL,
  "rrule" jsonb,
  "exdates" json DEFAULT '[]'::json NOT NULL,
  "propertyId" text,
  "organizationId" text NOT NULL,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP(3) NOT NULL,
PRIMARY KEY ("id"),
FOREIGN KEY ("calendarId") REFERENCES "Calendar" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='CalendarEvent_organizationId_startDate_idx') THEN
    CREATE INDEX "CalendarEvent_organizationId_startDate_idx" ON "CalendarEvent" USING btree ("organizationId", "startDate");
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='CalendarEvent_propertyId_idx') THEN
    CREATE INDEX "CalendarEvent_propertyId_idx" ON "CalendarEvent" USING btree ("propertyId");
  END IF;
END $ddl$;

CREATE TABLE IF NOT EXISTS "Notification" (
  "id" text NOT NULL,
  "title" text NOT NULL,
  "message" text NOT NULL,
  "priority" "NotificationPriority" DEFAULT 'INFO'::"NotificationPriority" NOT NULL,
  "scope" "NotificationScope" DEFAULT 'ORG'::"NotificationScope" NOT NULL,
  "source" text,
  "organizationId" text,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "acknowledged" BOOLEAN DEFAULT false NOT NULL,
PRIMARY KEY ("id"),
FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id") ON UPDATE CASCADE
);
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Notification_organizationId_idx') THEN
    CREATE INDEX "Notification_organizationId_idx" ON "Notification" USING btree ("organizationId");
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Notification_createdAt_idx') THEN
    CREATE INDEX "Notification_createdAt_idx" ON "Notification" USING btree ("createdAt");
  END IF;
END $ddl$;
DO $ddl$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='Notification_scope_createdAt_idx') THEN
    CREATE INDEX "Notification_scope_createdAt_idx" ON "Notification" USING btree (scope, "createdAt");
  END IF;
END $ddl$;
